// Mocks generated by Mockito 5.4.4 from annotations
// in product_management/test/screens/product_management/product_management_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter/material.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:native_dialog/native_dialog.dart' as _i5;
import 'package:product_management/data/models/api/response/response_data/response_data.dart'
    as _i2;
import 'package:product_management/data/repositories/api/response_data/response_data_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResponseData_0 extends _i1.SmartFake implements _i2.ResponseData {
  _FakeResponseData_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ResponseDataRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockResponseDataRepository extends _i1.Mock
    implements _i3.ResponseDataRepository {
  MockResponseDataRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ResponseData> getResponseData() => (super.noSuchMethod(
        Invocation.method(
          #getResponseData,
          [],
        ),
        returnValue: _i4.Future<_i2.ResponseData>.value(_FakeResponseData_0(
          this,
          Invocation.method(
            #getResponseData,
            [],
          ),
        )),
      ) as _i4.Future<_i2.ResponseData>);
}

/// A class which mocks [NativeDialog].
///
/// See the documentation for Mockito's code generation for more information.
class MockNativeDialog extends _i1.Mock implements _i5.NativeDialog {
  MockNativeDialog() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<String?> getPlatformVersion() => (super.noSuchMethod(
        Invocation.method(
          #getPlatformVersion,
          [],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  void showNativeAchievementView({
    required _i6.BuildContext? context,
    required String? name,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #showNativeAchievementView,
          [],
          {
            #context: context,
            #name: name,
          },
        ),
        returnValueForMissingStub: null,
      );
}
